include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true

  plugins:
    - dart_code_linter

dart_code_linter:

  metrics:
   cyclomatic-complexity: 7
   maximum-nesting: 2
   number-of-parameters: 5

  
