name: Flutter CI

on:
  push:
    branches:
      - '*'  # This triggers the workflow on any branch
  pull_request:
    branches:
      - '*'  # This also triggers on PRs for any branch

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.1'

    - name: Install dependencies
      run: |
        flutter pub get

    - name: Run tests and generate Allure report
      run: |
        dart run test_reporter -- flutter test
        allure serve

    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
