name: Flutter CI

on:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install Dependencies
        run: |
          flutter pub get

      - name: Run Flutter Tests
        run: |
          flutter test --coverage
          # If you're using a plugin like flutter_test_reporter:
          flutter pub global activate flutter_test_reporter
          flutter pub global run flutter_test_reporter --output-dir=test_report
        continue-on-error: false  # This ensures the workflow stops if tests fail

      - name: Install Allure Commandline
        run: |
          brew install allure
        continue-on-error: false  # Ensures the workflow stops if installation fails

      - name: Generate Allure Report
        run: |
          allure generate test_report --clean -o allure-report
        continue-on-error: false  # Ensures the workflow stops if report generation fails

      - name: Upload Allure Report as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
        continue-on-error: false  # Ensures the workflow stops if artifact upload fails
