name: "Build"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      #5 Install lcov
      - name: Install lcov
        run: brew install lcov

      #6 Run Tests
      - name: Run Tests
        id: test
        continue-on-error: true
        run: flutter test --coverage

      #7 Generate HTML Test Report
      - name: Generate HTML Test Report
        run: |
          genhtml coverage/lcov.info --output-directory coverage/html

      #8 Build Debug APK and AAB (Only if tests pass)
      - name: Build Debug APK and AAB
        if: success()
        run: |
          flutter build apk --debug
          flutter build appbundle --debug

      #9 Build Debug IPA (iOS Build)
      - name: Build Debug IPA
        if: success()
        run: flutter build ios --debug --no-codesign

      #10 Compress Archives and IPAs
      - name: Compress Archives and IPAs
        if: success()
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

      #11 Upload Artifacts if tests fail
      - name: Upload Coverage Artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Report
          path: coverage/html
