name: Flutter CI with Allure Report

on:
  push:
    branches:
      - '*'  # Trigger on any push to any branch
  pull_request:
    branches:
      - '*'  # Trigger on any PR to any branch

jobs:
  flutter_test:
    runs-on: ubuntu-latest  # Or macOS if you're working on a macOS-specific setup

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 1: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'  # Use your required Flutter version

    # Step 2: Install dependencies
    - name: Install dependencies
      run: |
        flutter pub get

    # Step 3: Run tests and generate allure results (you may need a custom plugin for Allure)
    - name: Run tests
      run: |
        flutter test --coverage  # You might also need to adjust for Allure

    # Step 4: Install Allure CLI
    - name: Install Allure CLI
      run: |
        # Install required dependencies
        sudo apt-get update
        sudo apt-get install -y wget openjdk-11-jdk
        # Download Allure CLI
        wget https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.tgz
        tar -zxvf allure-2.14.0.tgz
        sudo mv allure-2.14.0 /opt/allure
        sudo ln -s /opt/allure/allure /usr/local/bin/allure
        # Verify installation
        allure --version

    # Step 5: Generate Allure report (you might need a plugin or custom command here)
    - name: Generate Allure report
      run: |
        allure generate allure-results --clean

    # Step 6: Upload Allure report as an artifact
    - name: Upload Allure report artifact
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report/
