name: "Build"

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build & Run Tests
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Install lcov
        run: brew install lcov

      - name: Run Tests
        id: test
        run: flutter test --coverage

      - name: Generate Coverage Report
        run: |
          genhtml coverage/lcov.info --output-directory=coverage/lcov-report

      - name: Upload Test Coverage Report (Fail Case)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: coverage/lcov-report

  build_artifacts:
    name: Build & Upload Artifacts
    runs-on: macos-latest
    needs: build
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Debug APK and AAB
        run: |
          flutter build apk --debug
          flutter build appbundle --debug

      - name: Build Debug IPA (iOS Build)
        run: flutter build ios --debug --no-codesign

      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

      - name: Upload Build Artifacts with Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: Build-and-Coverage
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/bundle/debug/app-debug.aab
            build/ios_build.tar.gz
            coverage/lcov-report

  upload_to_drive:
    name: Upload Build-and-Coverage ZIP to Google Drive
    runs-on: ubuntu-latest
    needs: build_artifacts
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build & Coverage Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build-and-Coverage
          path: artifacts

      - name: Compress Build-and-Coverage to ZIP
        run: |
          cd artifacts
          zip -r ../Build-and-Coverage.zip .
          cd ..

      - name: Upload Build-and-Coverage ZIP to Google Drive
        uses: willo32/google-drive-upload-action@v1
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          parent_folder_id: ${{ secrets.FOLDERID }}
          target: Build-and-Coverage.zip

  upload_report_on_failure:
    name: Upload Coverage Report to Google Drive (Failure Case)
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Test Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: test-coverage-report
          path: coverage/lcov-report

      - name: Upload a file to Google Drive
        uses: willo32/google-drive-upload-action@v1
        with:
          target: coverage/lcov-report
          credentials: ${{ secrets.CREDENTIALS }}
          parent_folder_id: ${{ secrets.FOLDERID }}     
