name: Dart

on:
  push:
    branches: ["**"]

jobs:
  test_report:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable

      - name: Run Test
        run: dart run test_reporter -- flutter test

      - name: Aggregate Test Results
        run: |
          rm -rf allure-results
          mkdir allure-results-tmp
          find . -path "*/allure-results/*" -type f -exec cp '{}' ./allure-results-tmp/ \;
          mv allure-results-tmp allure-results
          zip -r allure-results-v1.zip allure-results/
