name: Flutter CI

on:
  push:
    branches:
      - '*'  # This triggers the workflow on any branch
  pull_request:
    branches:
      - '*'  # This also triggers on PRs for any branch

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.22.2'

      - name: Install dependencies
        run: |
          flutter pub get
          dart pub global activate melos

      - name: Melos Bootstrap
        run: melos bs

      - name: Install Allure Commandline
        run: |
          brew install allure

      - name: Install dependencies with Melos
        run: melos allures:install

      - name: Generate dependencies with Melos
        run: melos generate

      # Consider passing '--fatal-infos' for stricter analysis.
      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        continue-on-error: true
        run: melos test

      - name: Aggregate results
        run: |
          rm -rf allure-results
          mkdir allure-results-tmp
          find . -path "*/allure-results/*" -type f -exec cp '{}' ./allure-results-tmp/ \;
          mv allure-results-tmp allure-results
          zip -r allure-results.zip allure-results/

      - name: Upload Allure report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-results.zip

      - name: Publish Allure report to GitHub Pages
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
