name: "Build"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Run Tests
    runs-on: macos-latest

    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      #5 Install lcov
      - name: Install lcov
        run: brew install lcov

      #6 Run Tests
      - name: Run Tests
        id: test
        continue-on-error: true
        run: flutter test --coverage

      #7 Generate Coverage Report (both on pass and failure)
      - name: Generate Coverage Report
        run: |
          genhtml coverage/lcov.info --output-directory=coverage/lcov-report

      #8 Upload Coverage Report as Separate Artifact (if tests fail)
      - name: Upload Test Coverage Report (Fail Case)
        if: failure()  # Only run if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: coverage/lcov-report

  build_artifacts:
    name: Build & Upload Artifacts
    runs-on: macos-latest
    needs: build
    if: success()  # This job only runs if tests pass
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Debug APK and AAB
        run: |
          flutter build apk --debug
          flutter build appbundle --debug

      - name: Build Debug IPA (iOS Build)
        run: flutter build ios --debug --no-codesign

      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

      #8 Merge and Upload Build Artifacts and Coverage Report (if tests pass)
      - name: Upload Build Artifacts with Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: Build and Coverage Artifacts
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/bundle/debug/app-debug.aab
            build/ios_build.tar.gz
            coverage/lcov-report
