name: Dart

on:
  push:
    branches: ["**"]

jobs:
  test_report:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable

      - name: Install Dependencies
        run: dart pub global activate melos

      - name: Verify Melos Installation
        run: melos --version

      - name: Check if Melos Workspace Exists
        run: |
          if [ ! -f "melos.yaml" ]; then
            echo "melos.yaml not found! Ensure you have set up Melos workspace."
            exit 1
          fi

      - name: Bootstrap Melos
        run: melos bs

      - name: Debug Melos Packages
        run: melos list

      - name: Install Allure Dependencies
        run: melos allures:install

      - name: Generate Reports
        run: melos generate

      - name: Analyze Project Source
        run: dart analyze

      - name: Run Tests
        continue-on-error: true
        run: melos test

      - name: Aggregate Test Results
        run: |
          rm -rf allure-results
          mkdir allure-results-tmp
          find . -path "*/allure-results/*" -type f -exec cp '{}' ./allure-results-tmp/ \;
          mv allure-results-tmp allure-results
          zip -r allure-results.zip allure-results/

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
