name: Flutter CI with Allure

on:
  push:
    branches:
      - '**'  # Trigger on pushes to any branch

jobs:
  flutter-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter 3.22.2
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Install dependencies
      run: flutter pub get

    - name: Install Allure CLI
      run: |
        curl -o allure-commandline.zip -L https://github.com/allure-framework/allure2/releases/download/2.16.1/allure-2.16.1.zip
        unzip allure-commandline.zip
        sudo mv allure-2.16.1/bin/allure /usr/local/bin/allure
        allure --version

    - name: Run Flutter tests and generate Allure results
      run: |
        # Run Flutter tests and generate results in Allure format
        flutter test --coverage
        allure generate coverage/lcov-report --clean -o allure-results

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report
        allure open allure-report

    - name: Upload Allure Report as Artifact (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
