name: Flutter Linting

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Dart Code Linter and Generate HTML Report
        run: dart run dart_code_linter:metrics analyze . --fatal-style --reporter=html --output-directory=lint_report

      - name: Upload Lint Report Artifact on Failure
        if: failure()  # Runs only if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: lint_report
