name: "Build"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      #5 Install lcov
      - name: Install lcov
        run: brew install lcov

      #6 Run Tests
      - name: Run Tests
        run: flutter test --coverage

      #7 Generate HTML Test Report
      - name: Generate HTML Test Report
        run: |
          genhtml coverage/lcov.info --output-directory coverage/html

      #8 Build Debug APK and AAB (Only if tests pass)
      - name: Build Debug APK and AAB
        if: success()
        run: |
          flutter build apk --debug
          flutter build appbundle --debug

      #9 Build Debug IPA (iOS Build)
      - name: Build Debug IPA
        if: success()
        run: flutter build ios --debug --no-codesign

      - name: Compress Archives and IPAs
        if: success()
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

      #10 Upload Artifacts
      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Debug Builds
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/bundle/debug/app-debug.aab
            build/ios_build.tar.gz
            coverage/html

      #11 Send Email with Debug APK and Test Report
      - name: Send Email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Flutter Build & Test Report"
          body: "Please find the attached Debug APK and Test Report."
          to: "krunalmkathikar1993@gmail.com"
          from: "CI/CD Pipeline"
          attachments: |
            build/app/outputs/flutter-apk/app-debug.apk
            coverage/html/index.html
