name: Flutter Lint Check

on: [push, pull_request]

jobs:
  lint:
    name: Run Dart Code Linter on Flutter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Dart Code Linter with Fatal Style and Generate Report
        run: |
          mkdir -p lint_reports
          flutter pub run dart_code_linter:metrics analyze lib --fatal-style --reporter=html > lint_reports/lint_report.html

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: lint_reports/
