name: Flutter Test and Allure Report (Linux)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-report:
    runs-on: ubuntu-latest  # Using Ubuntu (Linux)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests with Custom Reporter
        run: dart run test_reporter -- flutter test

      - name: Install Allure Manually
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz  # Download Allure
          tar -xvzf allure-2.18.1.tgz  # Extract Allure
          sudo mv allure-2.18.1 /opt/allure  # Move Allure to a global directory
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure  # Create a symlink to the allure executable

      - name: Verify Allure Installation
        run: allure --version  # Verify if Allure was installed successfully

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report  # Run Allure report generation

      - name: Test Marketplace Action (Allure Report)
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
