name: Flutter Linting

on:
  push:
    branches:
      - '**'  # Run on push to any branch

jobs:
  lint:
    runs-on: macos-latest  # Changed to macOS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get | tee flutter_pub_get.log

      - name: Run Dart Code Linter and Generate HTML Report
        run: dart run dart_code_linter:metrics analyze . --fatal-style --reporter=html --output-directory=lint_report | tee lint.log

      - name: Upload Lint Report Artifact on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: lint_report

  after_lint:
    needs: lint  # Runs only if 'lint' job succeeds
    runs-on: macos-latest  # Changed to macOS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get | tee flutter_pub_get.log

      - name: Install lcov
        run: brew install lcov | tee lcov_install.log

      - name: Run Tests
        id: test
        run: flutter test --coverage | tee test.log  # Test failures will cause this step to fail

      - name: Generate Coverage Report (Runs Even If Tests Fail)
        if: always()
        run: genhtml coverage/lcov.info --output-directory=coverage/lcov-report | tee coverage.log
          
      - name: Upload Coverage Report (Runs Even If Tests Fail)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov-report
