name: Flutter Linting

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0' # Change to your Flutter version if needed

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Dart Code Linter
        run: |
          flutter pub run dart_code_linter:metrics analyze lib --reporter=html --output-directory=lint_report
        continue-on-error: true

      - name: Upload Lint Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: lint_report
