name: Flutter Test and Allure Report (Linux)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-report:
    runs-on: ubuntu-latest  # Change to Linux (Ubuntu)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests with Custom Reporter
        run: dart run test_reporter -- flutter test

      - name: Install Allure (Linux)
        run: |
          sudo apt update
          sudo apt install -y allure  # Ensure Allure is installed on Linux

      - name: Generate Allure Report
        run: allure generate build/allure-results --clean -o allure-report  # Run Allure report generation

      - name: Test Marketplace Action (Allure Report)
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
